name: Demo
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run PowerShell command
        run: |
          Write-Output "Run command executed"
        shell: pwsh

  test:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run PowerShell command
        run: |
          Write-Output "test executed"
      
