
name: Demo
on:
  push:
    branches: [main]

jobs:
  runs-on: windows-latest
  build:    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run PowerShell command
        run: |
          Write-Output "Run command executed"

  test:    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run PowerShell command
        run: |
          Write-Output "test executed"   
